/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.l3vels.sdk.model

import com.l3vels.sdk.model.Asset

import com.squareup.moshi.Json

/**
 * 
 *
 * @param items Number of assets to return per page
 * @param total Number of total items
 * @param limit Number of items to return per page
 * @param page Page number
 */


data class AssetsResponseDto (

    /* Number of assets to return per page */
    @Json(name = "items")
    val items: kotlin.collections.List<Asset>,

    /* Number of total items */
    @Json(name = "total")
    val total: java.math.BigDecimal,

    /* Number of items to return per page */
    @Json(name = "limit")
    val limit: java.math.BigDecimal,

    /* Page number */
    @Json(name = "page")
    val page: java.math.BigDecimal

)

