/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.l3vels.sdk.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name The name of the player.
 * @param projectId Game/project ID to create the player for. Example: Create player Jack for game Fortnite.
 * @param uniqueId You can send your generated unique ID for player if it's handy for game. If field is empty, we will generate unique ID.
 * @param username The username of the player.
 * @param email The email of the player.
 * @param avatar The image URL of the player avatar.
 * @param isCreateWallet Should create wallet for player or not.
 * @param customProps Custom props for player.
 */


data class CreatePlayerDto (

    /* The name of the player. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Game/project ID to create the player for. Example: Create player Jack for game Fortnite. */
    @Json(name = "project_id")
    val projectId: kotlin.String,

    /* You can send your generated unique ID for player if it's handy for game. If field is empty, we will generate unique ID. */
    @Json(name = "unique_id")
    val uniqueId: kotlin.String? = null,

    /* The username of the player. */
    @Json(name = "username")
    val username: kotlin.String? = null,

    /* The email of the player. */
    @Json(name = "email")
    val email: kotlin.String? = null,

    /* The image URL of the player avatar. */
    @Json(name = "avatar")
    val avatar: kotlin.String? = null,

    /* Should create wallet for player or not. */
    @Json(name = "is_create_wallet")
    val isCreateWallet: kotlin.Boolean? = null,

    /* Custom props for player. */
    @Json(name = "custom_props")
    val customProps: kotlin.collections.List<kotlin.String>? = null

)

