/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.l3vels.sdk.model

import com.l3vels.sdk.model.MintDtoAsset

import com.squareup.moshi.Json

/**
 * 
 *
 * @param projectId Game/project ID. Example: Call of Duty
 * @param collectionId Collection ID to use. Example: Characters, Weapons, etc.
 * @param asset 
 * @param contractId Contract ID
 * @param playerAddress Player address to mint token to. You can provide player ID or player address
 * @param playerId Player ID to mint to. You can provide player ID or player address
 */


data class MintDto (

    /* Game/project ID. Example: Call of Duty */
    @Json(name = "project_id")
    val projectId: kotlin.String,

    /* Collection ID to use. Example: Characters, Weapons, etc. */
    @Json(name = "collection_id")
    val collectionId: kotlin.String,

    @Json(name = "asset")
    val asset: MintDtoAsset,

    /* Contract ID */
    @Json(name = "contract_id")
    val contractId: kotlin.String? = null,

    /* Player address to mint token to. You can provide player ID or player address */
    @Json(name = "player_address")
    val playerAddress: kotlin.String? = null,

    /* Player ID to mint to. You can provide player ID or player address */
    @Json(name = "player_id")
    val playerId: kotlin.String? = null

)

