/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.l3vels.sdk.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param projectId Project Id
 * @param collectionId Collection Id
 * @param playerAddress Player address to mint token to
 * @param playerId Player ID to mint to. You can provide this or player_address
 * @param assets Array of tokens to mint
 */


data class MintBatchDto (

    /* Project Id */
    @Json(name = "project_id")
    val projectId: kotlin.String,

    /* Collection Id */
    @Json(name = "collection_id")
    val collectionId: kotlin.String,

    /* Player address to mint token to */
    @Json(name = "player_address")
    val playerAddress: kotlin.String,

    /* Player ID to mint to. You can provide this or player_address */
    @Json(name = "player_id")
    val playerId: kotlin.String,

    /* Array of tokens to mint */
    @Json(name = "assets")
    val assets: kotlin.collections.List<kotlin.String>

)

