/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.l3vels.sdk.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The unique identifier for the Player asset entity.
 * @param amount The amount of the specific asset that the player has.
 * @param playerId The unique identifier of the player that the asset is associated with.
 * @param assetId The unique identifier of the asset that the asset is associated with.
 * @param collectionId The unique identifier of the collection that the Player asset is associated with.
 * @param accountId The unique identifier of the account that the Player belongs to.
 * @param projectId The unique identifier of the project that the Player is associated with. This allows developers to organize their players by project and helps with tracking and reporting.
 * @param createdOn The date when the player was created.
 * @param modifiedOn The date when the player was last modified.
 * @param createdBy The Id of the user who created the player.
 * @param modifiedBy The Id of the user who last modified the player.
 */


data class PlayerAsset (

    /* The unique identifier for the Player asset entity. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The amount of the specific asset that the player has. */
    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    /* The unique identifier of the player that the asset is associated with. */
    @Json(name = "player_id")
    val playerId: kotlin.String,

    /* The unique identifier of the asset that the asset is associated with. */
    @Json(name = "asset_id")
    val assetId: kotlin.String,

    /* The unique identifier of the collection that the Player asset is associated with. */
    @Json(name = "collection_id")
    val collectionId: kotlin.String,

    /* The unique identifier of the account that the Player belongs to. */
    @Json(name = "account_id")
    val accountId: java.math.BigDecimal,

    /* The unique identifier of the project that the Player is associated with. This allows developers to organize their players by project and helps with tracking and reporting. */
    @Json(name = "project_id")
    val projectId: kotlin.String,

    /* The date when the player was created. */
    @Json(name = "created_on")
    val createdOn: java.time.OffsetDateTime,

    /* The date when the player was last modified. */
    @Json(name = "modified_on")
    val modifiedOn: java.time.OffsetDateTime,

    /* The Id of the user who created the player. */
    @Json(name = "created_by")
    val createdBy: java.math.BigDecimal,

    /* The Id of the user who last modified the player. */
    @Json(name = "modified_by")
    val modifiedBy: java.math.BigDecimal

)

