/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.l3vels.sdk.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param projectId Project Id
 * @param collectionId Collection Id
 * @param contractUri Contract URI
 */


data class SetContractUriDto (

    /* Project Id */
    @Json(name = "project_id")
    val projectId: kotlin.String,

    /* Collection Id */
    @Json(name = "collection_id")
    val collectionId: kotlin.String,

    /* Contract URI */
    @Json(name = "contract_uri")
    val contractUri: kotlin.String

)

