/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.l3vels.sdk.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param projectId Project Id
 * @param collectionId Collection Id
 * @param saleStatus Sale Status of the contract
 */


data class SetSaleStatusDto (

    /* Project Id */
    @Json(name = "project_id")
    val projectId: kotlin.String,

    /* Collection Id */
    @Json(name = "collection_id")
    val collectionId: kotlin.String,

    /* Sale Status of the contract */
    @Json(name = "sale_status")
    val saleStatus: kotlin.Any

)

