/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.l3vels.sdk.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param collectionId Collection ID to find and update the asset in. Example: Update AK-47 asset in Weapons collection.
 * @param projectId Game/project ID to update the asset in. Example: Call of Duty
 * @param name The name of the asset.
 * @param description The story of asset.
 * @param price Price of asset
 * @param supply Supply of asset
 * @param assetUrl Asset URL
 * @param customProps Custom props for asset.
 */


data class UpdateAssetDto (

    /* Collection ID to find and update the asset in. Example: Update AK-47 asset in Weapons collection. */
    @Json(name = "collection_id")
    val collectionId: kotlin.String,

    /* Game/project ID to update the asset in. Example: Call of Duty */
    @Json(name = "project_id")
    val projectId: kotlin.String,

    /* The name of the asset. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The story of asset. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Price of asset */
    @Json(name = "price")
    val price: java.math.BigDecimal? = null,

    /* Supply of asset */
    @Json(name = "supply")
    val supply: java.math.BigDecimal? = null,

    /* Asset URL */
    @Json(name = "asset_url")
    val assetUrl: kotlin.String? = null,

    /* Custom props for asset. */
    @Json(name = "custom_props")
    val customProps: kotlin.Any? = null

)

